### ISSUE TITLE
Category CRUD

### ISSUE THREAD

**Issue by ayleeee** [SeokCheol-Lee/FISA-Step04-MiniProject#2]
## Category CRUD
카테고리 CRUD 개발

## TO-DO
- [x] createCategory(String name)
- [x] getCategoryAll()
- [x] getCategoryById(int id)
- [x] updateCategory(int catId, String catName)
- [x] deleteCategory(int id)
