### ISSUE TITLE
Board CRUD

### ISSUE THREAD

**Issue by Oodls** [SeokCheol-Lee/FISA-Step04-MiniProject#3]
## 🛠️ 작업 설명
>Board entity관련 CRUD 구현

## 🔍 Todo
> 

 

- [x] createBoard(int userId, int catId, String name, String, context, String image) - test완료
- [x] getBoardAll() - test완료
- [x] getBoardInPage(Integer page) -test완료
- [x] getBoardByTitle(String title) 
- [x] getBoardById(int id)
- [ ] getBoardByTitleInPage(String title , Integer page)
- [x] updateBoardName(int boardId String boardName)
- [x] updateBoardContext(int boardId, String context)
- [x] updateImage(int boardId, String image)
- [x] updateCategory(int catId, String catName)
- [x] deleteBoard(int id);

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
